// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NameScreen(Props) {
  return React.createElement("div", {
              className: "flex h-screen"
            }, React.createElement("div", {
                  className: "bg-black h-screen w-screen flex flex-col justify-center items-center text-white"
                }, "yo"));
}

var make = NameScreen;

export {
  make ,
  
}
/* react Not a pure module */
