// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NameScreen(Props) {
  return React.createElement("div", {
              className: "bg-black"
            }, "yo");
}

var make = NameScreen;

export {
  make ,
  
}
/* react Not a pure module */
