// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Navbar(Props) {
  return React.createElement("nav", {
              className: "bg-gray-800"
            });
}

var make = Navbar;

export {
  make ,
  
}
/* react Not a pure module */
