// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import LogoSvg from "./logo.svg";
import * as NameScreen from "./screens/NameScreen.bs.js";

import './App.css';
;

var logo = LogoSvg;

function App(Props) {
  return React.createElement(NameScreen.make, {});
}

var make = App;

export {
  logo ,
  make ,
  
}
/*  Not a pure module */
