// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import LogoSvg from "./logo.svg";

import './App.css';
;

var logo = LogoSvg;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, "yo");
}

var make = App;

export {
  logo ,
  make ,
  
}
/*  Not a pure module */
